### ISSUE TITLE
Why there are so much duplicates lines here?

### ISSUE THREAD

**Issue by Perlover** [nuxt/http#137]
https://github.com/nuxt/http/blob/d6947d018c10db2cedcc3084ffd0d0b5a80f3fa3/lib/module.js#L156

I think it's misprints?

**Comment by Atinux** [comment]
Nice catch @Perlover 

Do you mind opening a PR to remove these duplicated lines?

**Comment by Perlover** [comment]
@Atinux I will do it (a PR) in next week ;)
