### ISSUE TITLE
onResponse hook is not working

### ISSUE THREAD

**Issue by lapwat** [nuxt/http#151]
This code is printing a **Request** object instead of a **Response** object.

```js
// ~/plugins/http.js
export default function ({ $http, $toast }) {
  $http.onResponse(response => {
    console.log(response)
  })
}
```

Result

![image](https://user-images.githubusercontent.com/7073651/100554496-48edec00-3295-11eb-83e7-882bfd9424dd.png)

**Comment by inhal** [comment]
Too, please help me! @pi0

**Comment by Gu3** [comment]
Yep, the doc is not correct : look the example and not the declaration 
https://http.nuxtjs.org/hooks#onresponse

**Comment by Geminii** [comment]
> @Geminii do you mind taking a look at it?

Yes i will to check and correct it

**Comment by Gu3** [comment]
I already made a PR about that : https://github.com/nuxt/http/pull/159 😉

**Comment by Geminii** [comment]
> I already made a PR about that : https://github.com/nuxt/http/pull/159 😉

Thanks about it 👍

**Comment by lapwat** [comment]
@Geminii @Atinux @Gu3 Thank you all for dealing with this issue!
