### ISSUE TITLE
KY universal 0.9.0 has just been released with ESM Support

### ISSUE THREAD

**Issue by husayt** [nuxt/http#161]
That should help to remove workarounds we  have here

**Comment by pi0** [comment]
Hi @husayt thanks for update. Actually i don't think we will use ky-universal again since it might introduce regressions again and global polyfill method might change in future (also next major version drops ky itself)

**Comment by husayt** [comment]
@pi0 just out of interest, what is going to be used instead of ky in next version?

**Comment by pi0** [comment]
@husayt Most probably via a `@nuxt/fetch` module with [ohmyfetch](https://github.com/nuxt-contrib/ohmyfetch) (both http and axios have legacy API and configration which is not suitable for future versions to support in module fetch and CAPI)
