### ISSUE TITLE
Allow access to baseURL?

### ISSUE THREAD

**Issue by sundowndev** [nuxt/http#164]
Hi, I need to access baseURL property in a template, is it possible to add a getter for it?

Thanks

**Comment by sundowndev** [comment]
> By simply looking at https://github.com/nuxt/http/blob/master/lib/plugin.js#L17
> 
> You should be able to use `this.$http._defaults.prefixUrl`. What would be the usage of accessing the `baseURL`?

Let's say I have a property `url` from my REST API, I'd like this url be a link in my template. Problem is this URL is not always absolute (e.g: /uploads/123.pdf). So I need a way to use the prefixUrl when needed.

`this.$http._defaults.prefixUrl` does not seem to have a TS signature, this is intended to be a private property, isn't it?

**Comment by pi0** [comment]
PR welcome to expose `$http.baseURL` but generally it would be much better if exposing baseURL via runtime config (`$config.baseURL`) to generate such links instead of depending on http client instance

**Comment by sundowndev** [comment]
Fixed by #165
