### ISSUE TITLE
import of type for JSONValue missing

### ISSUE THREAD

**Issue by Lisiadito** [nuxt/http#27]
Using the @nuxt/http module with TypeScript leads to an error `Cannot find name JSONValue`
The type `JSONValue` must be imported from `ky`.

**I can't open an issue via CMTY because the link is not working.**

**Comment by Lisiadito** [comment]
I would like to open a pull request for that problem but I think I don't have the permission to push to this repository.

**Comment by pi0** [comment]
Fixed in `@nuxt/http@0.1.2`
