### ISSUE TITLE
Cannot generate dynamic routes with nuxt generate

### ISSUE THREAD

**Issue by bovas85** [nuxt/http#44]
### Version

[^0.1.2](https://github.com/http/releases/tag/^0.1.2)

### Reproduction link

[https://github.com/bovas85/nunziellasalluce.com](https://github.com/bovas85/nunziellasalluce.com)

### Steps to reproduce

Clone the repo
yarn
yarn generate

axios is not being used, ky is used instead which fails after timing out

### What is expected ?

axios is used in nuxt.config as per imported

### What is actually happening?

axios is not being used, ky is used instead which fails after timing out

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/http/issues/c3">#c3</a>)</em></sub></div>

**Comment by bovas85** [comment]
Logs here
```
10:54:13 PM: 21:54:13 error with API Request timed out
10:54:13 PM:   at node_modules/ky/umd.js:131:11
10:54:13 PM:   at runNextTicks (internal/process/task_queues.js:55:5)
10:54:13 PM:   at listOnTimeout (internal/timers.js:501:9)
10:54:13 PM:   at processTimers (internal/timers.js:475:7)``

**Comment by pi0** [comment]
This error was related to timeout. Timeout is disabled by default in >=0.3.0
