### ISSUE TITLE
Globally set options.Credentials

### ISSUE THREAD

**Issue by darthf1** [nuxt/http#92]
Hi. Is there a way to globally set `options.credentials = 'include'`? I tried with the `onRequest` hook but then I get a TS error.

```js
import { Plugin } from '@nuxt/types'

const httpPlugin: Plugin = ({ $http }) => {
  $http.onRequest((config) => {
    config.credentials = 'include'
  })
}

export default httpPlugin
```
```
`TS2540: Cannot assign to 'credentials' because it is a read-only property.`
```
If I add a `// @ts-ignore` on this error, the request won't be made. If I remove the code all together, the request is made.

Is there another way to set this globally instead of every request?

**Comment by wildan2711** [comment]
Did you find solution? I need this too.

**Comment by darthf1** [comment]
No solution unfortunately

**Comment by desislavsd** [comment]
You may create a plugin and add the following:
```javascript
export default ( { $http } ) => {

    $http._defaults.credentials = 'include'; 
}
```

**Comment by notiv-nt** [comment]
+1 for the commend above, and don't forget to add plugin to the nuxt.config.js
