### ISSUE TITLE
Unable to get server error message on catch

### ISSUE THREAD

**Issue by lightmyfire17** [nuxt/http#97]
### Version

[v0.5.0](https://github.com/http/releases/tag/v0.5.0)

### Reproduction link

[https://jsfiddle.net/eobk1pam/1/](https://jsfiddle.net/eobk1pam/1/)

### Steps to reproduce

Use any HTTP Methods via $http ($get, delete, $put, etc.), try to catch the error like:
` this.$http
    .$get("http://nuxthttperrors.io/error")
    .then(resp => console.log(resp))
    .catch(e => console.log(e.response.data));
`

### What is expected ?

Expected to get the error response message, like in `network` tab in chrome. 

P.S. Working like a charm in axios.

### What is actually happening?

The error response object is always empty: 
`{
 name: "HTTPError",
 response: {}
}
`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/http/issues/c26">#c26</a>)</em></sub></div>

**Comment by dekadentno** [comment]
Try to write the catch block like this:
`
.catch(async err => {
        let error = await err.response.json();
        console.log('error: ', error);
      })
`

**Comment by Atinux** [comment]
Hi @dekadentno 

This has been fixed in https://github.com/nuxt/http/pull/113 and available in https://github.com/nuxt/http/releases/tag/v0.5.4

Keep in mind that `err.response` can be `undefined` if the request cannot hit the server.

**Comment by lightmyfire17** [comment]
Great, thanks.
